from repository.stock_repository import StockRepository
from repository.stock_repository_disk import StockRepositoryDisk
from repository.stock_repository_db import StockRepositoryDB
from services.equity_service import EquityService